FROM node

ARG RAILWAY_ENVIRONMENT
RAILWAY_DOCKERFILE_PATH=/build/Dockerfile
# Establece el directorio de trabajo
WORKDIR /app

# Copia el yarn.lock y package.json
COPY package.json yarn.lock ./

# Instala las dependencias
RUN yarn install

# Copia el resto del código de la aplicación
COPY . .

# Establece las variables de entorno necesarias
ENV PORT=3000
ENV DATABASE_URL=http://localhost:3000
ENV S3_BUCKET_NAME=keystone-test
ENV S3_REGION=ap-southeast-2
ENV S3_ACCESS_KEY_ID=keystone
ENV S3_SECRET_ACCESS_KEY=keystone

# Compila el proyecto
RUN yarn build

# Expone el puerto en el que la aplicación va a correr
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["yarn", "start"]
