# Usar una imagen oficial de Node.js como base
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y yarn.lock al directorio de trabajo
COPY package.json yarn.lock ./

# Instalar dependencias
RUN yarn install --frozen-lockfile

# Copiar el resto del código de la aplicación
COPY . .

# Construir la aplicación
RUN yarn build

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Definir el comando para iniciar la aplicación
CMD ["yarn", "start"]
