# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia el yarn.lock y package.json
COPY package.json yarn.lock ./

# Instala las dependencias
RUN yarn install

# Copia el resto del código de la aplicación
COPY . .

# Establece las variables de entorno necesarias
ENV PORT=3000
ENV DATABASE_URL=http://localhost:3000

# Compila el proyecto
RUN yarn build

# Expone el puerto en el que la aplicación va a correr
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["yarn", "start"]
